"""initial_baseline

Revision ID: d534ad5ae8e0
Revises: 
Create Date: 2026-05-31 22:42:50.784920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd534ad5ae8e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chapter_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('real_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('selected_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_version_id'], ['chapter_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_metrics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blueprint_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_evaluations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider_url', sa.Text(), nullable=True),
    sa.Column('llm_provider_api_key', sa.Text(), nullable=True),
    sa.Column('llm_provider_model', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('novel_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_projects_user_id'), 'novel_projects', ['user_id'], unique=False)
    op.create_table('user_daily_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_date', name='uq_user_daily')
    )
    op.create_index(op.f('ix_user_daily_requests_user_id'), 'user_daily_requests', ['user_id'], unique=False)
    op.create_table('blueprint_characters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identity', sa.String(length=255), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('relationship_to_protagonist', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint_relationships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('character_from', sa.String(length=255), nullable=False),
    sa.Column('character_to', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_blueprints',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('suspense_density', sa.String(length=32), nullable=True),
    sa.Column('foreshadowing_ops', sa.String(length=128), nullable=True),
    sa.Column('cognitive_twist_level', sa.Integer(), nullable=False),
    sa.Column('chapter_function', sa.String(length=32), nullable=True),
    sa.Column('chapter_focus', sa.String(length=255), nullable=True),
    sa.Column('suspense_type', sa.String(length=128), nullable=True),
    sa.Column('emotional_arc', sa.String(length=255), nullable=True),
    sa.Column('involved_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('mission_constraints', sa.JSON(), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('director_script', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('beat_sheet', sa.JSON(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blueprint_project_chapter', 'chapter_blueprints', ['project_id', 'chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_blueprints_chapter_number'), 'chapter_blueprints', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_blueprints_project_id'), 'chapter_blueprints', ['project_id'], unique=False)
    op.create_table('chapter_outlines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('global_summary_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('character_states_snapshot', sa.JSON(), nullable=True),
    sa.Column('plot_arcs_snapshot', sa.JSON(), nullable=True),
    sa.Column('chapter_summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_snapshots_chapter_number'), 'chapter_snapshots', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_snapshots_project_id'), 'chapter_snapshots', ['project_id'], unique=False)
    op.create_table('factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faction_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('leader', sa.String(length=255), nullable=True),
    sa.Column('hierarchy', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.String(length=64), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('recent_events', sa.JSON(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('traditions', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_project_id'), 'factions', ['project_id'], unique=False)
    op.create_table('foreshadowing_analysis',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('total_foreshadowings', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('abandoned_count', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_distance', sa.Float(), nullable=True),
    sa.Column('unresolved_ratio', sa.Float(), nullable=True),
    sa.Column('pattern_analysis', sa.JSON(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('foreshadowings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_chapter_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('target_reveal_chapter', sa.Integer(), nullable=True),
    sa.Column('reveal_method', sa.Text(), nullable=True),
    sa.Column('reveal_impact', sa.Text(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_plots', sa.JSON(), nullable=True),
    sa.Column('related_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('importance', sa.String(length=32), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('author_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_foreshadowing_project_status', 'foreshadowings', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_foreshadowings_project_id'), 'foreshadowings', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadowings_status'), 'foreshadowings', ['status'], unique=False)
    op.create_table('novel_blueprints',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.Column('tone', sa.String(length=128), nullable=True),
    sa.Column('one_sentence_summary', sa.Text(), nullable=True),
    sa.Column('full_synopsis', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('world_setting', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('novel_constitutions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('core_theme', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('core_conflict', sa.String(length=255), nullable=True),
    sa.Column('story_direction', sa.String(length=255), nullable=True),
    sa.Column('core_values', sa.Text(), nullable=True),
    sa.Column('pov_type', sa.String(length=64), nullable=True),
    sa.Column('pov_character', sa.String(length=255), nullable=True),
    sa.Column('pov_restrictions', sa.Text(), nullable=True),
    sa.Column('target_age_group', sa.String(length=64), nullable=True),
    sa.Column('reading_level', sa.String(length=64), nullable=True),
    sa.Column('violence_rating', sa.String(length=64), nullable=True),
    sa.Column('romance_rating', sa.String(length=64), nullable=True),
    sa.Column('overall_tone', sa.String(length=128), nullable=True),
    sa.Column('realism_level', sa.String(length=128), nullable=True),
    sa.Column('language_style', sa.String(length=128), nullable=True),
    sa.Column('world_type', sa.String(length=128), nullable=True),
    sa.Column('power_system', sa.Text(), nullable=True),
    sa.Column('world_rules', sa.JSON(), nullable=True),
    sa.Column('forbidden_content', sa.JSON(), nullable=True),
    sa.Column('allowed_character_types', sa.JSON(), nullable=True),
    sa.Column('character_power_limits', sa.Text(), nullable=True),
    sa.Column('allowed_relationship_types', sa.JSON(), nullable=True),
    sa.Column('allowed_plot_types', sa.JSON(), nullable=True),
    sa.Column('twist_frequency', sa.String(length=128), nullable=True),
    sa.Column('foreshadowing_rules', sa.Text(), nullable=True),
    sa.Column('time_span', sa.String(length=128), nullable=True),
    sa.Column('geographical_scope', sa.String(length=128), nullable=True),
    sa.Column('time_flow', sa.String(length=128), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('novel_conversations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('global_summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('plot_arcs', sa.JSON(), nullable=True),
    sa.Column('story_timeline_summary', sa.Text(), nullable=True),
    sa.Column('last_updated_chapter', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memories_project_id'), 'project_memories', ['project_id'], unique=True)
    op.create_table('story_time_trackers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('time_system', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('current_date', sa.String(length=64), nullable=True),
    sa.Column('current_time', sa.String(length=64), nullable=True),
    sa.Column('default_chapter_duration', sa.String(length=64), nullable=True),
    sa.Column('chapter_time_map', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('story_date', sa.String(length=64), nullable=True),
    sa.Column('time_elapsed', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('caused_by_event_id', sa.BigInteger(), nullable=True),
    sa.Column('leads_to_event_ids', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('is_turning_point', sa.Boolean(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caused_by_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_chapter_number'), 'timeline_events', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    op.create_table('writer_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=64), nullable=True),
    sa.Column('sentence_rhythm', sa.Text(), nullable=True),
    sa.Column('vocabulary_preferences', sa.JSON(), nullable=True),
    sa.Column('unique_expressions', sa.JSON(), nullable=True),
    sa.Column('formality_level', sa.String(length=64), nullable=True),
    sa.Column('opening_style', sa.Text(), nullable=True),
    sa.Column('transition_style', sa.Text(), nullable=True),
    sa.Column('ending_style', sa.Text(), nullable=True),
    sa.Column('dialogue_style', sa.Text(), nullable=True),
    sa.Column('dialogue_tags', sa.Text(), nullable=True),
    sa.Column('description_style', sa.Text(), nullable=True),
    sa.Column('show_vs_tell_ratio', sa.String(length=64), nullable=True),
    sa.Column('sensory_focus', sa.JSON(), nullable=True),
    sa.Column('catchphrases', sa.JSON(), nullable=True),
    sa.Column('personal_quirks', sa.JSON(), nullable=True),
    sa.Column('imperfection_patterns', sa.JSON(), nullable=True),
    sa.Column('thinking_pauses', sa.JSON(), nullable=True),
    sa.Column('filler_words', sa.JSON(), nullable=True),
    sa.Column('regional_expressions', sa.JSON(), nullable=True),
    sa.Column('avoid_patterns', sa.JSON(), nullable=True),
    sa.Column('variation_rules', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writer_personas_project_id'), 'writer_personas', ['project_id'], unique=False)
    op.create_table('causal_chains',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('cause_type', sa.String(length=64), nullable=True),
    sa.Column('cause_description', sa.Text(), nullable=False),
    sa.Column('cause_chapter', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=64), nullable=True),
    sa.Column('effect_description', sa.Text(), nullable=False),
    sa.Column('effect_chapter', sa.Integer(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('cause_event_id', sa.BigInteger(), nullable=True),
    sa.Column('effect_event_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resolution_description', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['effect_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causal_chains_project_id'), 'causal_chains', ['project_id'], unique=False)
    op.create_table('character_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_detail', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('emotion_intensity', sa.Integer(), nullable=True),
    sa.Column('emotion_reason', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('inventory_changes', sa.JSON(), nullable=True),
    sa.Column('relationship_changes', sa.JSON(), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('power_changes', sa.JSON(), nullable=True),
    sa.Column('known_secrets', sa.JSON(), nullable=True),
    sa.Column('new_knowledge', sa.JSON(), nullable=True),
    sa.Column('current_goals', sa.JSON(), nullable=True),
    sa.Column('goal_progress', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_states_chapter_number'), 'character_states', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_character_states_character_id'), 'character_states', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_states_project_id'), 'character_states', ['project_id'], unique=False)
    op.create_table('faction_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_members_project_id'), 'faction_members', ['project_id'], unique=False)
    op.create_table('faction_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_from_id', sa.Integer(), nullable=False),
    sa.Column('faction_to_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('established_at', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['faction_from_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_to_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_relationships_project_id'), 'faction_relationships', ['project_id'], unique=False)
    op.create_table('foreshadowing_reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('suggested_chapter_range', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadowing_reminders_project_id'), 'foreshadowing_reminders', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadowing_reminders_status'), 'foreshadowing_reminders', ['status'], unique=False)
    op.create_table('foreshadowing_resolutions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_number', sa.Integer(), nullable=False),
    sa.Column('resolution_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('resolution_type', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('reader_satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_at_chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadowing_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faction_relationship_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('old_type', sa.String(length=64), nullable=True),
    sa.Column('new_type', sa.String(length=64), nullable=False),
    sa.Column('old_strength', sa.Integer(), nullable=True),
    sa.Column('new_strength', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['faction_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faction_relationship_history')
    op.drop_table('foreshadowing_status_history')
    op.drop_table('foreshadowing_resolutions')
    op.drop_index(op.f('ix_foreshadowing_reminders_status'), table_name='foreshadowing_reminders')
    op.drop_index(op.f('ix_foreshadowing_reminders_project_id'), table_name='foreshadowing_reminders')
    op.drop_table('foreshadowing_reminders')
    op.drop_index(op.f('ix_faction_relationships_project_id'), table_name='faction_relationships')
    op.drop_table('faction_relationships')
    op.drop_index(op.f('ix_faction_members_project_id'), table_name='faction_members')
    op.drop_table('faction_members')
    op.drop_index(op.f('ix_character_states_project_id'), table_name='character_states')
    op.drop_index(op.f('ix_character_states_character_id'), table_name='character_states')
    op.drop_index(op.f('ix_character_states_chapter_number'), table_name='character_states')
    op.drop_table('character_states')
    op.drop_index(op.f('ix_causal_chains_project_id'), table_name='causal_chains')
    op.drop_table('causal_chains')
    op.drop_index(op.f('ix_writer_personas_project_id'), table_name='writer_personas')
    op.drop_table('writer_personas')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_chapter_number'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('story_time_trackers')
    op.drop_index(op.f('ix_project_memories_project_id'), table_name='project_memories')
    op.drop_table('project_memories')
    op.drop_table('novel_conversations')
    op.drop_table('novel_constitutions')
    op.drop_table('novel_blueprints')
    op.drop_index(op.f('ix_foreshadowings_status'), table_name='foreshadowings')
    op.drop_index(op.f('ix_foreshadowings_project_id'), table_name='foreshadowings')
    op.drop_index('ix_foreshadowing_project_status', table_name='foreshadowings')
    op.drop_table('foreshadowings')
    op.drop_table('foreshadowing_analysis')
    op.drop_index(op.f('ix_factions_project_id'), table_name='factions')
    op.drop_table('factions')
    op.drop_index(op.f('ix_chapter_snapshots_project_id'), table_name='chapter_snapshots')
    op.drop_index(op.f('ix_chapter_snapshots_chapter_number'), table_name='chapter_snapshots')
    op.drop_table('chapter_snapshots')
    op.drop_table('chapter_outlines')
    op.drop_index(op.f('ix_chapter_blueprints_project_id'), table_name='chapter_blueprints')
    op.drop_index(op.f('ix_chapter_blueprints_chapter_number'), table_name='chapter_blueprints')
    op.drop_index('ix_blueprint_project_chapter', table_name='chapter_blueprints')
    op.drop_table('chapter_blueprints')
    op.drop_table('blueprint_relationships')
    op.drop_table('blueprint_characters')
    op.drop_index(op.f('ix_user_daily_requests_user_id'), table_name='user_daily_requests')
    op.drop_table('user_daily_requests')
    op.drop_index(op.f('ix_novel_projects_user_id'), table_name='novel_projects')
    op.drop_table('novel_projects')
    op.drop_table('llm_configs')
    op.drop_table('chapter_evaluations')
    op.drop_table('blueprint_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('usage_metrics')
    op.drop_table('update_logs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_table('chapters')
    op.drop_table('chapter_versions')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
